### ISSUE TITLE
BUG - Adding “Primary Residence” to Assets table appears as “primaryResidence” not “Primary Residence” (see screenshot)

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#203]
<img width="1158" alt="bug" src="https://user-images.githubusercontent.com/8509047/67250607-a8ba7680-f489-11e9-865c-f80343e48efd.png">

**Comment by moewiz** [comment]
@sdharmarajah 
When we add a new row by clicking on one of the Types (see screenshot below), because we don't have a default investment for each different type, the `investment` field always is `primaryResidence`.
So please provide me the default investment for each type and I consider this issue is an enhancement.
![image](https://user-images.githubusercontent.com/12948375/67256594-2db98600-f4b2-11e9-8861-63fb7943b1ee.png)
