### ISSUE TITLE
DEMO TASK - Clear all data in all "Partner" tabs

### ISSUE THREAD

**Issue by sdharmarajah** [kodiakorg/financial#213]
See below for examples

Need to clear from:
- "Product Optimizer" section
- all pull out drawers in "Strategy" section

<img width="1002" alt="1" src="https://user-images.githubusercontent.com/8509047/67357581-404bc200-f57b-11e9-8cdb-2bb968c7bece.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/8509047/67357582-404bc200-f57b-11e9-8cd4-ad601595bbcd.png">

**Comment by moewiz** [comment]
@sdharmarajah 
Please note, in order to build a Plain English sentence, the partner's name comes from the backend (for now, we use the default JSON).
![image](https://user-images.githubusercontent.com/12948375/67453415-cd147f80-f650-11e9-9d44-1960c390f4fb.png)

![image](https://user-images.githubusercontent.com/12948375/67453396-c5ed7180-f650-11e9-98f7-f537541dd201.png)

**Comment by sdharmarajah** [comment]
Hi @moewiz
This issue is about the data in the tabs in the pull out drawer

We just need to clear those 

Not the plain English sentences

**Comment by sdharmarajah** [comment]
We need to keep the Partner tab

Just **clear the data** from the partner tab (no data)

@moewiz

**Comment by moewiz** [comment]
Fixed: https://github.com/kodiakorg/financial-planning-dashboard/pull/90
